name: CI / CD LIEGENTGAME
on:
  push:
    branches:
      - main

jobs:
  Docker_Build_And_Push:
    runs-on: ubuntu-22.04

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set YAML file
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" | base64 --decode > ./src/main/resources/application-prod.yml
          find src

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. 현재 디렉토리 파일 리스트 확인 (디버깅 용도)
      - name: List files in current directory
        run: ls -la

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 --push --tag 5hseok/hallucination-server:0.0.1 -f ./Dockerfile .

  Deploy:
    needs: Docker_Build_And_Push
    runs-on: ubuntu-22.04

    steps:
      # EC2에 SSH로 연결하여 배포
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sh /home/ubuntu/deploy.sh